### ISSUE TITLE
Crash while selecting text in some situations

### ISSUE THREAD

**Issue by Rose2073** [Rose2073/CodeEditor#2]
Crash log:
java.lang.IllegalArgumentException: start > end
	at com.rose.editor.android.RoseEditor.setSelectionRegion(RoseEditor.java:2334)
	at com.rose.editor.android.EventHandler$SelectionHandle.applyPosition(EventHandler.java:558)
	at com.rose.editor.android.EventHandler.onTouchEvent(EventHandler.java:251)
	at com.rose.editor.android.RoseEditor.onTouchEvent(RoseEditor.java:2614)
	at android.view.View.dispatchTouchEvent(View.java:11843)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:555)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1894)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3508)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:508)
	at android.view.View.dispatchPointerEvent(View.java:12082)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5463)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5247)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4737)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4790)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4756)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4887)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4764)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4944)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4737)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4790)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4756)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4764)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4737)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7363)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7337)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7295)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7514)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:182)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7445)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7550)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:847)
	at android.view.Choreographer.doFrame(Choreographer.java:768)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1027)
	at android.os.Handler.handleCallback(Handler.java:809)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7555)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by Rose2073** [comment]
This probably caused by invalid handle in SelectionHandle or setSelectionRegion()

**Comment by Rose2073** [comment]
This exception never happens now and the cause of this exception remains unknown,
This issue will be reopened if it happens again.
